export { Agendamento } from './Agendamento'
export { Login } from './Login'
export { Exemplo } from './Exemplo'
export { Signup } from '../pages/Signup'
export { ChangePassword } from '../pages/ChangePassword'